# Setup
title:        Revision
tagline:      Lancaster University Exam Revision Questions + Answers
baseurl:      "/Exam-Revision/"
paginate:     1
locale:       "en"

collections:
  topics:
    output: true

# About/contact
author:
  name:       Harry Baines

# Gems
plugins:
  - jekyll-paginate

#Others
markdown: kramdown